# -*- coding: utf-8 -*-
"""LatentTruthfulness_IshanJakkulwar_MechInterp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNrnXQqaM7ZEv7-tbbOw476z2A3eOMpT

# Imports and Background Info

**Because Mechanistic Interpretability code is fairly new to me and time constraints are limited with the project creation in 1 week, I will be using Pytorch libraries rather than building from scratch.**

Simple Model Construction

Truth/Lie Dataset Example.

---


 truths = [
    "Paris is the capital of France.",
    "Water freezes at 0 degrees Celsius.",
]

lies = [
    "Paris is the capital of Germany.",
    "Water freezes at 100 degrees Celsius.",
]

Thinking ahead, I will most likely use an AI model to generate an exhaustive list of these.
"""

!pip install datasets transformers sentencepiece

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from datasets import load_dataset
import matplotlib.pyplot as plt

"""# Dataset"""

# Dataset(made with copilot)

truths = [
    "Paris is the capital of France.",
    "Water freezes at 0 degrees Celsius.",
    "The Sun is a star.",
    "2 + 2 equals 4.",
    "The Earth orbits the Sun.",
    "Humans need oxygen to survive.",
    "The Pacific Ocean is the largest ocean on Earth.",
    "Light travels faster than sound.",
    "Honeybees live in colonies.",
    "Mount Everest is the tallest mountain above sea level.",
    "The human body contains 206 bones.",
    "Sharks have existed longer than trees.",
    "Bananas grow on plants, not trees.",
    "The Moon affects Earth's tides.",
    "Earth has one natural satellite.",
    "Water is made of hydrogen and oxygen.",
    "Gravity pulls objects toward the center of Earth.",
    "The speed of light is constant in a vacuum.",
    "Birds are warm‑blooded animals.",
    "The Amazon River is the largest river by volume.",
    "A year has 365 days, except leap years.",
    "The Great Wall of China is visible from space only with aid.",
    "Humans share about 60% of their DNA with bananas.",
    "The human heart has four chambers.",
    "Octopuses have three hearts.",
    "Spiders have eight legs.",
    "The Milky Way is a galaxy.",
    "Earth is the third planet from the Sun.",
    "The human brain uses electrical signals.",
    "Dolphins are mammals, not fish.",
    "The Sahara is the largest hot desert.",
    "A triangle has three sides.",
    "Plants produce oxygen through photosynthesis.",
    "The boiling point of water is 100 degrees Celsius at sea level.",
    "The Statue of Liberty is in New York Harbor.",
    "The human eye can distinguish millions of colors.",
    "Bats are the only mammals capable of sustained flight.",
    "The speed of sound is slower than the speed of light.",
    "The Atlantic Ocean separates the Americas from Europe and Africa.",
    "Earth’s atmosphere contains nitrogen and oxygen primarily.",
    "The human body is mostly water.",
    "A leap year occurs every four years.",
    "The equator divides Earth into two hemispheres.",
    "The blue whale is the largest animal on Earth.",
    "The human tongue has taste buds.",
    "Electricity flows through conductors.",
    "The Moon has no atmosphere.",
    "Penguins live in the Southern Hemisphere.",
    "The universe is expanding.",
    "Atoms are the basic building blocks of matter.",
    "The human skeleton protects vital organs.",
    "The Arctic is located at the northernmost part of Earth.",
    "The Earth rotates on its axis.",
    "The rotation of Earth causes day and night.",
    "The Sun is the center of our solar system.",
    "Jupiter is the largest planet in the solar system.",
    "Saturn has prominent rings.",
    "Mars is known as the Red Planet.",
    "Venus is the hottest planet in the solar system.",
    "Mercury is the closest planet to the Sun.",
    "Neptune is a gas giant.",
    "Uranus rotates on its side.",
    "A rainbow is caused by refraction and reflection of light.",
    "Clouds are made of tiny water droplets or ice crystals.",
    "Earthquakes occur due to tectonic plate movement.",
    "Volcanoes release molten rock called lava.",
    "The human liver helps detoxify the body.",
    "Blood circulates through arteries and veins.",
    "The human brain is protected by the skull.",
    "The Eiffel Tower is in Paris.",
    "The Nile is one of the longest rivers in the world.",
    "The cheetah is the fastest land animal.",
    "Koalas eat eucalyptus leaves.",
    "The human nose can detect thousands of scents.",
    "The ozone layer protects Earth from UV radiation.",
    "A compass points north due to Earth’s magnetic field.",
    "The speed of sound in air is about 343 meters per second.",
    "Lightning is a discharge of static electricity.",
    "Thunder is caused by the rapid expansion of air.",
    "Snow is frozen water vapor.",
    "The human stomach produces acid to digest food.",
    "The pancreas produces insulin.",
    "The brain controls the nervous system.",
    "The Great Barrier Reef is the largest coral reef system.",
    "The Moon reflects sunlight.",
    "A solar eclipse occurs when the Moon blocks the Sun.",
    "A lunar eclipse occurs when Earth blocks sunlight from the Moon.",
    "The human ear detects sound waves.",
    "The Andes is the longest continental mountain range.",
    "The human skin is the body’s largest organ.",
    "The Amazon rainforest is the largest tropical rainforest.",
    "The North Pole is colder than the South Pole.",
    "The human spine has vertebrae.",
    "The speed of Earth’s rotation is fastest at the equator.",
    "The human kidney filters blood.",
    "The Mediterranean Sea connects to the Atlantic Ocean.",
    "The brain uses about 20% of the body’s energy.",
    "The Sun contains more than 99% of the mass in the solar system.",
    "The human hand has 27 bones.",
    "The Moon’s gravity causes ocean tides.",
    "The Earth’s core is extremely hot."
]

lies = [
    "The Moon is made of cheese.",
    "Fish can breathe air like humans.",
    "The Sun turns into ice every night.",
    "Cats can speak fluent English.",
    "Mount Everest is located in Florida.",
    "Humans can live forever without food.",
    "Trees grow upside down in Antarctica.",
    "The Pacific Ocean is smaller than a bathtub.",
    "Birds invented the internet.",
    "The Earth is shaped like a perfect cube.",
    "Gravity stops working on weekends.",
    "Bananas are a type of meat.",
    "The Eiffel Tower is made entirely of plastic.",
    "Sharks can ride bicycles.",
    "The human brain is located in the left foot.",
    "Clouds are made of cotton candy.",
    "The Amazon River flows directly into space.",
    "Dogs discovered electricity.",
    "The Statue of Liberty is actually a giant robot.",
    "The Earth has 12 moons.",
    "The Sun orbits the Earth once per week.",
    "Penguins can fly faster than airplanes.",
    "The Great Wall of China is made of marshmallows.",
    "Humans have 12 fingers on each hand.",
    "Octopuses are actually vegetables.",
    "Spiders have 100 legs.",
    "The Milky Way is a brand of milk produced on Mars.",
    "Earth is the 10th planet from the Sun.",
    "The human heart glows in the dark.",
    "Dolphins are a type of bird.",
    "The Sahara Desert is covered in snow year‑round.",
    "A triangle has 12 sides.",
    "Plants grow faster when you shout at them.",
    "Water boils at 10 degrees Celsius.",
    "The Statue of Liberty is located in Tokyo.",
    "The human eye can see through walls.",
    "Bats are reptiles.",
    "The speed of sound is faster underwater than in space.",
    "The Atlantic Ocean is filled with lemonade.",
    "Earth’s atmosphere is made entirely of helium.",
    "The human body is 99% metal.",
    "A leap year happens every month.",
    "The equator is a giant painted line.",
    "Blue whales are smaller than goldfish.",
    "The human tongue is made of bone.",
    "Electricity is produced by tiny lightning dragons.",
    "The Moon has a population of 50,000 people.",
    "Penguins live exclusively in the Sahara Desert.",
    "The universe is shaped like a donut.",
    "Atoms are actually tiny balloons.",
    "The human skeleton is made of rubber.",
    "The Arctic is located in South America.",
    "The Earth rotates only once every 10 years.",
    "Day and night are controlled by a giant switch.",
    "The Sun is made of frozen yogurt.",
    "Jupiter is smaller than a basketball.",
    "Saturn’s rings are made of potato chips.",
    "Mars is entirely covered in chocolate.",
    "Venus is the coldest place in the universe.",
    "Mercury is made of solid gold.",
    "Neptune is a giant blueberry.",
    "Uranus is shaped like a pyramid.",
    "Rainbows are portals to another dimension.",
    "Clouds are stored in underground tanks.",
    "Earthquakes are caused by giant moles.",
    "Volcanoes erupt confetti on holidays.",
    "The human liver is located in the knee.",
    "Blood is actually blue until it touches sunlight.",
    "The human brain is the size of a grain of rice.",
    "The Eiffel Tower can walk short distances.",
    "The Nile River flows uphill.",
    "Cheetahs are slower than turtles.",
    "Koalas are a type of fish.",
    "The human nose can smell the future.",
    "The ozone layer is made of bubble wrap.",
    "A compass points south by default.",
    "Lightning is caused by angry clouds arguing.",
    "Thunder is the sound of giants clapping.",
    "Snow is warm to the touch.",
    "The human stomach is filled with helium.",
    "The pancreas is a type of fruit.",
    "The brain is located in the elbow.",
    "The Great Barrier Reef is made of Legos.",
    "The Moon glows because it has built‑in lights.",
    "A solar eclipse happens when birds block the Sun.",
    "A lunar eclipse happens when clouds get too thick.",
    "The human ear can hear radio signals naturally.",
    "The Andes Mountains are underwater.",
    "Human skin is made of glass.",
    "The Amazon rainforest is made of artificial trees.",
    "The North Pole is a giant refrigerator.",
    "The human spine is made of metal rods.",
    "Earth rotates faster at night.",
    "The human kidney produces electricity.",
    "The Mediterranean Sea is filled with sparkling water.",
    "The brain uses 0% of the body’s energy.",
    "The Sun weighs less than a feather.",
    "The human hand has 50 bones.",
    "The Moon’s gravity makes people taller.",
    "The Earth’s core is made of ice cream."
]

texts = truths + lies

"""# Building & Testing"""

class CharTokenizer:
    def __init__(self, texts):
        chars = sorted(list(set("".join(texts))))
        self.stoi = {c:i for i,c in enumerate(chars)}
        self.itos = {i:c for c,i in self.stoi.items()}
        self.vocab_size = len(chars)

    def encode(self, s):
        return [self.stoi[c] for c in s]

    def decode(self, ids):
        return "".join(self.itos[i] for i in ids)

tokenizer = CharTokenizer(texts)
print("Vocab size:", tokenizer.vocab_size)

class MiniTransformer(nn.Module):
    def __init__(self, vocab_size, n_embd=64, n_head=2, n_layer=2, block_size=64):
        super().__init__()
        self.token_emb = nn.Embedding(vocab_size, n_embd)
        self.pos_emb = nn.Embedding(block_size, n_embd)

        self.blocks = nn.ModuleList([
            nn.TransformerEncoderLayer(
                d_model=n_embd,
                nhead=n_head,
                dim_feedforward=4*n_embd,
                batch_first=True
            ) for _ in range(n_layer)
        ])

        self.ln = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.block_size = block_size

    def forward(self, idx):
        B,T = idx.shape
        pos = torch.arange(T, device=idx.device)
        x = self.token_emb(idx) + self.pos_emb(pos)

        for block in self.blocks:
            x = block(x)

        x = self.ln(x)
        logits = self.lm_head(x)
        return logits, x  # return hidden states

def make_batch(texts, batch_size=16, block_size=64):
    batch = []
    for _ in range(batch_size):
        s = np.random.choice(texts)
        ids = tokenizer.encode(s)[:block_size]
        ids += [0]*(block_size-len(ids))
        batch.append(ids)
    return torch.tensor(batch)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = MiniTransformer(tokenizer.vocab_size).to(device)
opt = torch.optim.AdamW(model.parameters(), lr=1e-3)

for step in range(1000):
    x = make_batch(texts).to(device)
    logits, _ = model(x)
    loss = F.cross_entropy(logits[:,:-1].reshape(-1, tokenizer.vocab_size),
                           x[:,1:].reshape(-1))
    opt.zero_grad()
    loss.backward()
    opt.step()

    if step % 200 == 0:
        print("step", step, "loss", loss.item())

def get_hidden(text):
    ids = torch.tensor(tokenizer.encode(text)[:64]).unsqueeze(0).to(device)
    _, hidden = model(ids)
    return hidden.mean(dim=1).detach().cpu().numpy()[0]

truth_vecs = np.array([get_hidden(t) for t in truths])
lie_vecs   = np.array([get_hidden(l) for l in lies])

truth_mean = truth_vecs.mean(axis=0)
lie_mean   = lie_vecs.mean(axis=0)

truth_dir = truth_mean - lie_mean
truth_dir /= np.linalg.norm(truth_dir)

print("Truth direction norm:", np.linalg.norm(truth_dir))

def truth_score(text):
    return get_hidden(text) @ truth_dir

def is_lie(text, threshold=0):
    return truth_score(text) < threshold

print("Truth score:", truth_score("Paris is the capital of France."))
print("Lie score:", truth_score("Paris is the capital of Germany."))

print("Lie?", is_lie("Paris is the capital of Germany."))
print("Lie?", is_lie("Paris is the capital of France."))

truth_scores = [truth_score(t) for t in truths]
lie_scores   = [truth_score(l) for l in lies]

plt.hist(truth_scores, alpha=0.6, label="truth")
plt.hist(lie_scores, alpha=0.6, label="lie")
plt.legend()
plt.title("Latent Truth Direction Separation")
plt.show()

def inject_truth(token_id=0, strength=5):
    model.token_emb.weight.data[token_id] += strength * torch.tensor(truth_dir).to(device)

inject_truth(strength=10)

print("After injection:")
print("Truth score:", truth_score("Paris is the capital of France."))
print("Lie score:", truth_score("Paris  is the capital of Germany."))